name: Main Foodgram workflow

on:
  push:
    branches:
      - main

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.10
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: foodgram
        ports:
          - 5432:5432

        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:

    - name: Check out code
      uses: actions/checkout@v4
      

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install ruff==0.8.0
        pip install -r ./backend/requirements.txt


    - name: Lint with ruff and run django tests
      env:
        POSTGRES_DB: foodgram
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        DB_HOST: db
        DB_PORT: 5432
      run: |
        python -m ruff check backend/
        cd backend/
        python manage.py test